### PR TITLE
added MsgPack

### PR DESCRIPTION
**Pull request by volth**
added MsgPack (unofficial serializer from https://bitbucket.org/jaroslav/scala-macro-serialization/src)

### CODE REVIEW

**Comment by dkomanov** [comment]
Hi, could you use msgpack from Maven repo, not via jar?

**Comment by volth** [comment]
This library (the only one using macros) is not uploaded to maven.
I can include source, it is a single file.

**Comment by dkomanov** [comment]
Let's try with source.
And rename to MsgPackMacros, just to not mislead reader.

**Comment by volth** [comment]
Just discovered bintray.com which is much easier for publishing jars than maven.org. So I uploaded the jar (actually its newer version) there.
Class name is also renamed.

**Comment by dkomanov** [comment]
No, still, it's strange (and not secure) to use some repo as well as a jar.

**Comment by volth** [comment]
OK, forget it.
I will not take the job of uploading it to maven.org (seeing no difference how it could be more "secure" than github.com or bintray.com), it would a take whole day.

**Pull request closed without merging**
